package board

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/codcod/pickle/internal/config"
	"github.com/codcod/pickle/internal/ticket"
)

func testCfg() *config.Config {
	return &config.Config{Projects: []config.Project{
		{Name: "demo", Path: ".", WIPInDevelopment: 1, WIPInReview: 1},
	}}
}

// ticketBody renders a minimal, parseable ticket file. hist is the full History
// bullet list (one line per entry, already "- YYYY-MM-DD — ..." formatted).
func ticketBody(id, title, impact, hist string) string {
	return fmt.Sprintf(`---
id: %s
title: %s
project: demo
depends-on: []
spawned-by: []
impact: %s
complexity: medium
cost: M
---

# %s — %s

## History

%s
`, id, title, impact, id, title, hist)
}

// mkTicket writes a ticket file into root/tickets/<dir>/.
func mkTicket(t *testing.T, root, dir, id, slug, body string) {
	t.Helper()
	p := filepath.Join(root, "tickets", dir, id+"-"+slug+".md")
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func loadTree(t *testing.T, root string) []*ticket.Ticket {
	t.Helper()
	tickets, issues := ticket.LoadAll(root)
	if len(issues) > 0 {
		t.Fatalf("load issues: %v", issues)
	}
	return tickets
}

const created = "- 2026-07-20 — created (TO DO). source: test"

func TestRenderGolden(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	mkTicket(t, root, "1-to-do", "T-002", "beta", ticketBody("T-002", "Beta", "medium", created))
	mkTicket(t, root, "6-done", "T-003", "gamma", ticketBody("T-003", "Gamma", "high",
		created+"\n- 2026-07-21 — IN REVIEW → DONE\n- 2026-07-22 — merged to main (abc1234)"))
	mkTicket(t, root, "7-dropped", "T-004", "delta", ticketBody("T-004", "Delta", "low",
		created+"\n- 2026-07-21 — TO DO → DROPPED: superseded by T-001"))

	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	want := `<!-- generated by pickle — do not edit; run pickle board sync -->

# Board

This file is generated from the ticket files (the single source of truth) by
` + "`pickle ticket new`, `pickle ticket move` and `pickle board sync`" + `. Do not edit it by
hand — edit the tickets. Hand-written planning notes live in [` + "`NOTES.md`" + `](NOTES.md).

**WIP limits (per child-project):**
- ` + "`demo`: `3-in-development/` ≤ 1 · `4-in-review/` ≤ 1" + `

Last updated: 2026-07-26

## IN DEVELOPMENT

### demo (0/1)

| id | title | depends-on |
|---|---|---|

## IN REVIEW

### demo (0/1)

| id | title | depends-on |
|---|---|---|

## REWORK

### demo

| id | title | open findings |
|---|---|---|

## READY (impact order, per child)

### demo

| id | title | impact | complexity | cost | depends-on |
|---|---|---|---|---|---|

## TO DO (impact order, per child)

### demo

| id | title | impact | complexity | cost | depends-on |
|---|---|---|---|---|---|
| T-001 | Alpha | high | medium | M | [] |
| T-002 | Beta | medium | medium | M | [] |

## DONE

### demo

| id | title | merged |
|---|---|---|
| T-003 | Gamma | yes — merged to main (abc1234) |

## DROPPED

### demo

| id | title | reason |
|---|---|---|
| T-004 | Delta | superseded by T-001 |
`
	if got != want {
		t.Errorf("golden mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderIsPure: same inputs ⇒ byte-identical output.
func TestRenderIsPure(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	tickets, cfg := loadTree(t, root), testCfg()
	if Render(tickets, cfg, "2026-07-26") != Render(tickets, cfg, "2026-07-26") {
		t.Error("two renders of the same inputs differ")
	}
}

// TestRenderSanitizesCells: a pipe or newline in a cell can never split a table
// row — the T-014·2/T-034 bug class is unrepresentable by construction.
func TestRenderSanitizesCells(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "evil", ticketBody("T-001", "evil | pipe title", "high", created))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-001 | evil ¦ pipe title | high |") {
		t.Errorf("pipe not sanitised to ¦:\n%s", got)
	}
	// CR/LF (unreachable via ticket new, which rejects them, but the renderer
	// must hold on its own): collapse to a single space.
	tk := &ticket.Ticket{ID: "T-009", Num: 9, Dir: "1-to-do",
		Front: map[string]string{"title": "a\r\nb", "impact": "high", "complexity": "low", "cost": "S", "project": "demo"}}
	got = Render([]*ticket.Ticket{tk}, testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-009 | a b | high |") {
		t.Errorf("newline not collapsed:\n%s", got)
	}
}

// cellsIn returns the trimmed cells of the board row for id. Splitting on `|` is
// safe because sanitizeCell substitutes every `|` in a value for `¦`.
func cellsIn(t *testing.T, rendered, id string) []string {
	t.Helper()
	for _, ln := range strings.Split(rendered, "\n") {
		ln = strings.TrimSpace(ln)
		if !strings.HasPrefix(ln, "| "+id+" |") {
			continue
		}
		parts := strings.Split(strings.Trim(ln, "|"), "|")
		out := make([]string, len(parts))
		for i, p := range parts {
			out[i] = strings.TrimSpace(p)
		}
		return out
	}
	t.Fatalf("no board row for %s in:\n%s", id, rendered)
	return nil
}

// titleCell renders a single TO DO ticket carrying title and returns its rendered
// title cell.
func titleCell(t *testing.T, title string) string {
	t.Helper()
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "slug", ticketBody("T-001", title, "high", created))
	return cellsIn(t, Render(loadTree(t, root), testCfg(), "2026-07-26"), "T-001")[1]
}

// TestRenderCapsCellWidth: no rendered cell exceeds maxCellRunes, the cap counts
// runes (never bytes), and it runs after the ¦ substitution (T-049).
func TestRenderCapsCellWidth(t *testing.T) {
	// 1 — an over-long value is truncated to exactly the cap, ellipsis included.
	t.Run("truncates to exactly the cap", func(t *testing.T) {
		got := titleCell(t, strings.Repeat("a", 300))
		// Rune count, not len(): a byte assertion would pass on a mid-rune cut.
		if n := utf8.RuneCountInString(got); n != maxCellRunes {
			t.Errorf("cell width = %d runes, want %d: %q", n, maxCellRunes, got)
		}
		if !strings.HasSuffix(got, "…") {
			t.Errorf("truncated cell does not end in an ellipsis: %q", got)
		}
		if want := strings.Repeat("a", maxCellRunes-1) + "…"; got != want {
			t.Errorf("cell = %q, want %q", got, want)
		}
	})

	// 2 — the boundary: at or below the cap nothing is touched.
	t.Run("boundary", func(t *testing.T) {
		for _, n := range []int{maxCellRunes - 1, maxCellRunes, maxCellRunes + 1} {
			in := strings.Repeat("b", n)
			got := titleCell(t, in)
			switch {
			case n <= maxCellRunes:
				if got != in {
					t.Errorf("%d-rune cell was altered: %q", n, got)
				}
				if strings.Contains(got, "…") {
					t.Errorf("%d-rune cell gained an ellipsis: %q", n, got)
				}
			default:
				if utf8.RuneCountInString(got) != maxCellRunes || !strings.HasSuffix(got, "…") {
					t.Errorf("%d-rune cell not capped: %q", n, got)
				}
			}
		}
	})

	// 3 — multi-byte input must never be cut mid-rune.
	t.Run("never cuts mid-rune", func(t *testing.T) {
		for _, in := range []string{strings.Repeat("é", 200), strings.Repeat("世", 200)} {
			got := titleCell(t, in)
			if !utf8.ValidString(got) {
				t.Errorf("cell is not valid UTF-8: %q", got)
			}
			if strings.ContainsRune(got, '\uFFFD') {
				t.Errorf("cell contains U+FFFD (mid-rune cut): %q", got)
			}
			if n := utf8.RuneCountInString(got); n != maxCellRunes {
				t.Errorf("cell width = %d runes, want %d", n, maxCellRunes)
			}
		}
	})

	// 4 — substitution and cap compose: an over-long run of pipes is both
	// substituted and capped, and the row keeps exactly one `|` per column
	// boundary (the integrity the substitution exists for). Note this does *not*
	// pin the two steps' order: `|` → `¦` is a one-for-one rune substitution, so
	// it cannot change the rune count either way — see the T-049 History note.
	t.Run("substitution and cap compose", func(t *testing.T) {
		root := t.TempDir()
		mkTicket(t, root, "1-to-do", "T-001", "pipes",
			ticketBody("T-001", strings.Repeat("|", 200), "high", created))
		rendered := Render(loadTree(t, root), testCfg(), "2026-07-26")
		got := cellsIn(t, rendered, "T-001")[1]
		if want := strings.Repeat("¦", maxCellRunes-1) + "…"; got != want {
			t.Errorf("cell = %q, want %d ¦ then an ellipsis", got, maxCellRunes-1)
		}
		// A stray `|` would split the row — the invariant the substitution exists for.
		for _, ln := range strings.Split(rendered, "\n") {
			if strings.HasPrefix(ln, "| T-001 |") && strings.Count(ln, "|") != 7 {
				t.Errorf("row has %d pipes, want 7 (one per column boundary): %s",
					strings.Count(ln, "|"), ln)
			}
		}
	})

	// 5/6 — a capped `merged` cell keeps its prefix and the ref (truncation is
	// head-preserving), and still agrees with ticket.HasMergeLine.
	t.Run("merged cell keeps prefix and ref", func(t *testing.T) {
		root := t.TempDir()
		// A migration-shaped merge note: the ref sits early, then paragraphs of prose.
		mergeLine := "- 2026-07-22 — merged to main (abc1234) after " +
			strings.Repeat("pipeline noise ", 40)
		body := ticketBody("T-001", "Verbose", "high",
			created+"\n- 2026-07-21 — IN REVIEW → DONE\n"+mergeLine)
		mkTicket(t, root, "6-done", "T-001", "verbose", body)

		tickets := loadTree(t, root)
		got := cellsIn(t, Render(tickets, testCfg(), "2026-07-26"), "T-001")[2]

		if n := utf8.RuneCountInString(got); n != maxCellRunes {
			t.Errorf("merged cell width = %d runes, want %d: %q", n, maxCellRunes, got)
		}
		if !strings.HasPrefix(got, "yes — ") {
			t.Errorf("merged cell lost its prefix: %q", got)
		}
		if !strings.Contains(got, "abc1234") {
			t.Errorf("merged cell lost the ref (truncation must be head-preserving): %q", got)
		}
		// The gate check and the cell must never disagree (T-044 decision 3).
		if !ticket.HasMergeLine(tickets[0].Text) {
			t.Error("HasMergeLine = false for a ticket whose merge line was capped in the cell")
		}
		if strings.Contains(got, "no — publish-gated") {
			t.Errorf("merged ticket rendered as unmerged: %q", got)
		}
	})
}

// TestRenderWIPCounts: the (n/limit) counts are computed at render time (T-014·1).
func TestRenderWIPCounts(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "3-in-development", "T-001", "alpha", ticketBody("T-001", "Alpha", "high",
		created+"\n- 2026-07-21 — READY → IN DEVELOPMENT"))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "### demo (1/1)") {
		t.Errorf("IN DEVELOPMENT count not computed:\n%s", got)
	}
	if !strings.Contains(got, "### demo (0/1)") {
		t.Errorf("IN REVIEW count not computed:\n%s", got)
	}
}

// TestRenderDerivedTerminalCells: DONE merged / DROPPED reason / REWORK open
// findings come from the ticket's History, never from a previous board (D3).
func TestRenderDerivedTerminalCells(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "6-done", "T-001", "unmerged", ticketBody("T-001", "Unmerged", "high",
		created+"\n- 2026-07-21 — IN REVIEW → DONE"))
	mkTicket(t, root, "5-rework", "T-002", "sent-back", ticketBody("T-002", "SentBack", "high",
		created+"\n- 2026-07-21 — IN REVIEW → REWORK: two blocking findings"))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-001 | Unmerged | no — publish-gated |") {
		t.Errorf("unmerged DONE cell wrong:\n%s", got)
	}
	if !strings.Contains(got, "| T-002 | SentBack | two blocking findings |") {
		t.Errorf("REWORK open-findings cell not derived from History:\n%s", got)
	}
}

// TestRenderOrdering: TO DO/READY by impact desc, ties by id asc (D1).
func TestRenderOrdering(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-003", "c", ticketBody("T-003", "C", "high", created))
	mkTicket(t, root, "1-to-do", "T-001", "a", ticketBody("T-001", "A", "medium", created))
	mkTicket(t, root, "1-to-do", "T-002", "b", ticketBody("T-002", "B", "high", created))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	i2, i3, i1 := strings.Index(got, "| T-002 |"), strings.Index(got, "| T-003 |"), strings.Index(got, "| T-001 |")
	if !(i2 < i3 && i3 < i1) {
		t.Errorf("order wrong (want T-002, T-003, T-001):\n%s", got)
	}
}

func TestNormalizeLastUpdated(t *testing.T) {
	a := "x\nLast updated: 2026-07-26\ny"
	b := "x\nLast updated: 2020-01-01\ny"
	if NormalizeLastUpdated(a) != NormalizeLastUpdated(b) {
		t.Error("date-only difference should normalise away")
	}
	if NormalizeLastUpdated(a) == NormalizeLastUpdated("x\nLast updated: 2026-07-26\nz") {
		t.Error("real difference must survive normalisation")
	}
}

func TestRegenerate(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	if err := Regenerate(root, testCfg()); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, "tickets", "BOARD.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "| T-001 | Alpha |") {
		t.Errorf("regenerated board missing row:\n%s", data)
	}
	// Refuses on structural load problems rather than silently omitting tickets.
	mkTicket(t, root, "1-to-do", "NOPE", "x", "no frontmatter")
	if err := Regenerate(root, testCfg()); err == nil {
		t.Error("expected Regenerate to refuse on load problems")
	}
}

const sampleBoard = `# Board

## IN DEVELOPMENT

### pickle (1/1)

| id | title | depends-on |
|---|---|---|
| T-002 | audit | [T-001] |

## TO DO (impact order, per child)

### pickle

| id | title |
|---|---|
| T-NNN | template placeholder |
| T-003 | new |

### web

| id | title |
|---|---|
| T-050 | webby |

## Dependency chain

- T-001 → T-002
`

func TestParse(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "BOARD.md")
	if err := os.WriteFile(path, []byte(sampleBoard), 0o644); err != nil {
		t.Fatal(err)
	}
	rows, err := Parse(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 3 {
		t.Fatalf("expected 3 rows (placeholder + dependency-chain bullets excluded), got %d: %+v", len(rows), rows)
	}
	want := map[string]Row{
		"T-002": {Status: "IN DEVELOPMENT", Child: "pickle", ID: "T-002"},
		"T-003": {Status: "TO DO", Child: "pickle", ID: "T-003"},
		"T-050": {Status: "TO DO", Child: "web", ID: "T-050"},
	}
	for _, r := range rows {
		w, ok := want[r.ID]
		if !ok {
			t.Errorf("unexpected row %+v", r)
			continue
		}
		if r != w {
			t.Errorf("row %s = %+v, want %+v", r.ID, r, w)
		}
	}
}
