package board

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/codcod/pickle/internal/config"
	"github.com/codcod/pickle/internal/ticket"
)

func testCfg() *config.Config {
	return &config.Config{Projects: []config.Project{
		{Name: "demo", Path: ".", WIPInDevelopment: 1, WIPInReview: 1},
	}}
}

// ticketBody renders a minimal, parseable ticket file. hist is the full History
// bullet list (one line per entry, already "- YYYY-MM-DD — ..." formatted).
func ticketBody(id, title, impact, hist string) string {
	return fmt.Sprintf(`---
id: %s
title: %s
project: demo
depends-on: []
spawned-by: []
impact: %s
complexity: medium
cost: M
---

# %s — %s

## History

%s
`, id, title, impact, id, title, hist)
}

// mkTicket writes a ticket file into root/tickets/<dir>/.
func mkTicket(t *testing.T, root, dir, id, slug, body string) {
	t.Helper()
	p := filepath.Join(root, "tickets", dir, id+"-"+slug+".md")
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func loadTree(t *testing.T, root string) []*ticket.Ticket {
	t.Helper()
	tickets, issues := ticket.LoadAll(root)
	if len(issues) > 0 {
		t.Fatalf("load issues: %v", issues)
	}
	return tickets
}

const created = "- 2026-07-20 — created (TO DO). source: test"

func TestRenderGolden(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	mkTicket(t, root, "1-to-do", "T-002", "beta", ticketBody("T-002", "Beta", "medium", created))
	mkTicket(t, root, "6-done", "T-003", "gamma", ticketBody("T-003", "Gamma", "high",
		created+"\n- 2026-07-21 — IN REVIEW → DONE\n- 2026-07-22 — merged to main (abc1234)"))
	mkTicket(t, root, "7-dropped", "T-004", "delta", ticketBody("T-004", "Delta", "low",
		created+"\n- 2026-07-21 — TO DO → DROPPED: superseded by T-001"))

	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	want := `<!-- generated by pickle — do not edit; run pickle board sync -->

# Board

This file is generated from the ticket files (the single source of truth) by
` + "`pickle ticket new`, `pickle ticket move` and `pickle board sync`" + `. Do not edit it by
hand — edit the tickets. Hand-written planning notes live in [` + "`NOTES.md`" + `](NOTES.md).

**WIP limits (per child-project):**
- ` + "`demo`: `3-in-development/` ≤ 1 · `4-in-review/` ≤ 1" + `

Last updated: 2026-07-26

## IN DEVELOPMENT

### demo (0/1)

| id | title | depends-on |
|---|---|---|

## IN REVIEW

### demo (0/1)

| id | title | depends-on |
|---|---|---|

## REWORK

### demo

| id | title | open findings |
|---|---|---|

## READY (impact order, per child)

### demo

| id | title | impact | complexity | cost | depends-on |
|---|---|---|---|---|---|

## TO DO (impact order, per child)

### demo

| id | title | impact | complexity | cost | depends-on |
|---|---|---|---|---|---|
| T-001 | Alpha | high | medium | M | [] |
| T-002 | Beta | medium | medium | M | [] |

## DONE

### demo

| id | title | merged |
|---|---|---|
| T-003 | Gamma | yes — merged to main (abc1234) |

## DROPPED

### demo

| id | title | reason |
|---|---|---|
| T-004 | Delta | superseded by T-001 |
`
	if got != want {
		t.Errorf("golden mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestRenderIsPure: same inputs ⇒ byte-identical output.
func TestRenderIsPure(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	tickets, cfg := loadTree(t, root), testCfg()
	if Render(tickets, cfg, "2026-07-26") != Render(tickets, cfg, "2026-07-26") {
		t.Error("two renders of the same inputs differ")
	}
}

// TestRenderSanitizesCells: a pipe or newline in a cell can never split a table
// row — the T-014·2/T-034 bug class is unrepresentable by construction.
func TestRenderSanitizesCells(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "evil", ticketBody("T-001", "evil | pipe title", "high", created))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-001 | evil ¦ pipe title | high |") {
		t.Errorf("pipe not sanitised to ¦:\n%s", got)
	}
	// CR/LF (unreachable via ticket new, which rejects them, but the renderer
	// must hold on its own): collapse to a single space.
	tk := &ticket.Ticket{ID: "T-009", Num: 9, Dir: "1-to-do",
		Front: map[string]string{"title": "a\r\nb", "impact": "high", "complexity": "low", "cost": "S", "project": "demo"}}
	got = Render([]*ticket.Ticket{tk}, testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-009 | a b | high |") {
		t.Errorf("newline not collapsed:\n%s", got)
	}
}

// TestRenderWIPCounts: the (n/limit) counts are computed at render time (T-014·1).
func TestRenderWIPCounts(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "3-in-development", "T-001", "alpha", ticketBody("T-001", "Alpha", "high",
		created+"\n- 2026-07-21 — READY → IN DEVELOPMENT"))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "### demo (1/1)") {
		t.Errorf("IN DEVELOPMENT count not computed:\n%s", got)
	}
	if !strings.Contains(got, "### demo (0/1)") {
		t.Errorf("IN REVIEW count not computed:\n%s", got)
	}
}

// TestRenderDerivedTerminalCells: DONE merged / DROPPED reason / REWORK open
// findings come from the ticket's History, never from a previous board (D3).
func TestRenderDerivedTerminalCells(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "6-done", "T-001", "unmerged", ticketBody("T-001", "Unmerged", "high",
		created+"\n- 2026-07-21 — IN REVIEW → DONE"))
	mkTicket(t, root, "5-rework", "T-002", "sent-back", ticketBody("T-002", "SentBack", "high",
		created+"\n- 2026-07-21 — IN REVIEW → REWORK: two blocking findings"))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	if !strings.Contains(got, "| T-001 | Unmerged | no — publish-gated |") {
		t.Errorf("unmerged DONE cell wrong:\n%s", got)
	}
	if !strings.Contains(got, "| T-002 | SentBack | two blocking findings |") {
		t.Errorf("REWORK open-findings cell not derived from History:\n%s", got)
	}
}

// TestRenderOrdering: TO DO/READY by impact desc, ties by id asc (D1).
func TestRenderOrdering(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-003", "c", ticketBody("T-003", "C", "high", created))
	mkTicket(t, root, "1-to-do", "T-001", "a", ticketBody("T-001", "A", "medium", created))
	mkTicket(t, root, "1-to-do", "T-002", "b", ticketBody("T-002", "B", "high", created))
	got := Render(loadTree(t, root), testCfg(), "2026-07-26")
	i2, i3, i1 := strings.Index(got, "| T-002 |"), strings.Index(got, "| T-003 |"), strings.Index(got, "| T-001 |")
	if !(i2 < i3 && i3 < i1) {
		t.Errorf("order wrong (want T-002, T-003, T-001):\n%s", got)
	}
}

func TestNormalizeLastUpdated(t *testing.T) {
	a := "x\nLast updated: 2026-07-26\ny"
	b := "x\nLast updated: 2020-01-01\ny"
	if NormalizeLastUpdated(a) != NormalizeLastUpdated(b) {
		t.Error("date-only difference should normalise away")
	}
	if NormalizeLastUpdated(a) == NormalizeLastUpdated("x\nLast updated: 2026-07-26\nz") {
		t.Error("real difference must survive normalisation")
	}
}

func TestRegenerate(t *testing.T) {
	root := t.TempDir()
	mkTicket(t, root, "1-to-do", "T-001", "alpha", ticketBody("T-001", "Alpha", "high", created))
	if err := Regenerate(root, testCfg()); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, "tickets", "BOARD.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "| T-001 | Alpha |") {
		t.Errorf("regenerated board missing row:\n%s", data)
	}
	// Refuses on structural load problems rather than silently omitting tickets.
	mkTicket(t, root, "1-to-do", "NOPE", "x", "no frontmatter")
	if err := Regenerate(root, testCfg()); err == nil {
		t.Error("expected Regenerate to refuse on load problems")
	}
}

const sampleBoard = `# Board

## IN DEVELOPMENT

### pickle (1/1)

| id | title | depends-on |
|---|---|---|
| T-002 | audit | [T-001] |

## TO DO (impact order, per child)

### pickle

| id | title |
|---|---|
| T-NNN | template placeholder |
| T-003 | new |

### web

| id | title |
|---|---|
| T-050 | webby |

## Dependency chain

- T-001 → T-002
`

func TestParse(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "BOARD.md")
	if err := os.WriteFile(path, []byte(sampleBoard), 0o644); err != nil {
		t.Fatal(err)
	}
	rows, err := Parse(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 3 {
		t.Fatalf("expected 3 rows (placeholder + dependency-chain bullets excluded), got %d: %+v", len(rows), rows)
	}
	want := map[string]Row{
		"T-002": {Status: "IN DEVELOPMENT", Child: "pickle", ID: "T-002"},
		"T-003": {Status: "TO DO", Child: "pickle", ID: "T-003"},
		"T-050": {Status: "TO DO", Child: "web", ID: "T-050"},
	}
	for _, r := range rows {
		w, ok := want[r.ID]
		if !ok {
			t.Errorf("unexpected row %+v", r)
			continue
		}
		if r != w {
			t.Errorf("row %s = %+v, want %+v", r.ID, r, w)
		}
	}
}
